/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SelectAccountRouteImport } from './routes/select-account'
import { Route as VerifyAppointmentRouteImport } from './routes/verify-appointment'
import { Route as VerifyFileRouteImport } from './routes/verify-file'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedCorrespondenceRouteImport } from './routes/_authenticated/correspondence'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as InviteAcceptRouteImport } from './routes/invite.accept'
import { Route as LegalComplaintsRouteImport } from './routes/legal.complaints'
import { Route as LegalIpRouteImport } from './routes/legal.ip'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as MTokenRouteImport } from './routes/m.$token'
import { Route as MpTokenRouteImport } from './routes/mp.$token'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as AuthenticatedAdminReportTemplatesRouteImport } from './routes/_authenticated/admin.report-templates'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents.index'
import { Route as AuthenticatedDocumentsAnalyzeRouteImport } from './routes/_authenticated/documents.analyze'
import { Route as AuthenticatedDrawingsDrawingIdRouteImport } from './routes/_authenticated/drawings.$drawingId'
import { Route as AuthenticatedEntitiesNewRouteImport } from './routes/_authenticated/entities.new'
import { Route as AuthenticatedNNotificationIdRouteImport } from './routes/_authenticated/n.$notificationId'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform.index'
import { Route as AuthenticatedPlatformAuditRouteImport } from './routes/_authenticated/platform.audit'
import { Route as AuthenticatedPlatformBreachPlaybookRouteImport } from './routes/_authenticated/platform.breach-playbook'
import { Route as AuthenticatedPlatformBreakglassRouteImport } from './routes/_authenticated/platform.breakglass'
import { Route as AuthenticatedPlatformContentRouteImport } from './routes/_authenticated/platform.content'
import { Route as AuthenticatedPlatformDsrRouteImport } from './routes/_authenticated/platform.dsr'
import { Route as AuthenticatedPlatformEntitiesRouteImport } from './routes/_authenticated/platform.entities'
import { Route as AuthenticatedPlatformEscalationsRouteImport } from './routes/_authenticated/platform.escalations'
import { Route as AuthenticatedPlatformFlagsRouteImport } from './routes/_authenticated/platform.flags'
import { Route as AuthenticatedPlatformIncidentsRouteImport } from './routes/_authenticated/platform.incidents'
import { Route as AuthenticatedPlatformIntegrationsRouteImport } from './routes/_authenticated/platform.integrations'
import { Route as AuthenticatedPlatformLegalRouteImport } from './routes/_authenticated/platform.legal'
import { Route as AuthenticatedPlatformPrivacyRouteImport } from './routes/_authenticated/platform.privacy'
import { Route as AuthenticatedPlatformQueueRouteImport } from './routes/_authenticated/platform.queue'
import { Route as AuthenticatedPlatformReportTemplatesRouteImport } from './routes/_authenticated/platform.report-templates'
import { Route as AuthenticatedPlatformRequestsRouteImport } from './routes/_authenticated/platform.requests'
import { Route as AuthenticatedPlatformSlaRouteImport } from './routes/_authenticated/platform.sla'
import { Route as AuthenticatedPlatformStaffRouteImport } from './routes/_authenticated/platform.staff'
import { Route as AuthenticatedPlatformStudioRouteImport } from './routes/_authenticated/platform.studio'
import { Route as AuthenticatedPlatformUsersRouteImport } from './routes/_authenticated/platform.users'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties.index'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties.$propertyId'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated/properties.new'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests.index'
import { Route as AuthenticatedRequestsRequestIdRouteImport } from './routes/_authenticated/requests.$requestId'
import { Route as AuthenticatedSettingsMessagingRouteImport } from './routes/_authenticated/settings.messaging'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsPrivacyRouteImport } from './routes/_authenticated/settings.privacy'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedEntitiesEntityIdIndexRouteImport } from './routes/_authenticated/entities.$entityId.index'
import { Route as AuthenticatedEntitiesEntityIdInvitationsRouteImport } from './routes/_authenticated/entities.$entityId.invitations'
import { Route as AuthenticatedEntitiesEntityIdPublicProfileRouteImport } from './routes/_authenticated/entities.$entityId.public-profile'
import { Route as AuthenticatedEntitiesEntityIdReportTemplatesRouteImport } from './routes/_authenticated/entities.$entityId.report-templates'
import { Route as AuthenticatedEntitiesEntityIdTeamRouteImport } from './routes/_authenticated/entities.$entityId.team'
import { Route as AuthenticatedPlatformEntityEntityIdRouteImport } from './routes/_authenticated/platform.entity.$entityId'
import { Route as AuthenticatedPlatformUserUserIdRouteImport } from './routes/_authenticated/platform.user.$userId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects.$projectId.index'
import { Route as AuthenticatedProjectsProjectIdClosureRouteImport } from './routes/_authenticated/projects.$projectId.closure'
import { Route as AuthenticatedProjectsProjectIdContractsRouteImport } from './routes/_authenticated/projects.$projectId.contracts'
import { Route as AuthenticatedProjectsProjectIdDrawingsRouteImport } from './routes/_authenticated/projects.$projectId.drawings'
import { Route as AuthenticatedProjectsProjectIdDurationsRouteImport } from './routes/_authenticated/projects.$projectId.durations'
import { Route as AuthenticatedProjectsProjectIdFinanceRouteImport } from './routes/_authenticated/projects.$projectId.finance'
import { Route as AuthenticatedProjectsProjectIdMarketingRouteImport } from './routes/_authenticated/projects.$projectId.marketing'
import { Route as AuthenticatedProjectsProjectIdMediaRouteImport } from './routes/_authenticated/projects.$projectId.media'
import { Route as AuthenticatedProjectsProjectIdPartiesRouteImport } from './routes/_authenticated/projects.$projectId.parties'
import { Route as AuthenticatedProjectsProjectIdReportsRouteImport } from './routes/_authenticated/projects.$projectId.reports'
import { Route as AuthenticatedProjectsProjectIdRequestsRouteImport } from './routes/_authenticated/projects.$projectId.requests'
import { Route as AuthenticatedProjectsProjectIdServicesRouteImport } from './routes/_authenticated/projects.$projectId.services'
import { Route as AuthenticatedProjectsProjectIdStagesRouteImport } from './routes/_authenticated/projects.$projectId.stages'
import { Route as AuthenticatedProjectsProjectIdTeamRouteImport } from './routes/_authenticated/projects.$projectId.team'
import { Route as AuthenticatedProjectsProjectIdVisitsRouteImport } from './routes/_authenticated/projects.$projectId.visits'
import { Route as AuthenticatedProjectsProjectIdWarrantiesRouteImport } from './routes/_authenticated/projects.$projectId.warranties'
import { Route as ApiPublicCronDurationScanRouteImport } from './routes/api.public.cron.duration-scan'
import { Route as ApiPublicMailCallbackRouteImport } from './routes/api/public/mail/callback'
import { Route as AuthenticatedEntitiesEntityIdTemplateImportsImportIdRouteImport } from './routes/_authenticated/entities.$entityId.template-imports.$importId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectAccountRoute = SelectAccountRouteImport.update({
  id: '/select-account',
  path: '/select-account',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyAppointmentRoute = VerifyAppointmentRouteImport.update({
  id: '/verify-appointment',
  path: '/verify-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyFileRoute = VerifyFileRouteImport.update({
  id: '/verify-file',
  path: '/verify-file',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorrespondenceRoute =
  AuthenticatedCorrespondenceRouteImport.update({
    id: '/correspondence',
    path: '/correspondence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalComplaintsRoute = LegalComplaintsRouteImport.update({
  id: '/legal/complaints',
  path: '/legal/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIpRoute = LegalIpRouteImport.update({
  id: '/legal/ip',
  path: '/legal/ip',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MTokenRoute = MTokenRouteImport.update({
  id: '/m/$token',
  path: '/m/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MpTokenRoute = MpTokenRouteImport.update({
  id: '/mp/$token',
  path: '/mp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminReportTemplatesRoute =
  AuthenticatedAdminReportTemplatesRouteImport.update({
    id: '/admin/report-templates',
    path: '/admin/report-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsAnalyzeRoute =
  AuthenticatedDocumentsAnalyzeRouteImport.update({
    id: '/documents/analyze',
    path: '/documents/analyze',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDrawingsDrawingIdRoute =
  AuthenticatedDrawingsDrawingIdRouteImport.update({
    id: '/drawings/$drawingId',
    path: '/drawings/$drawingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesNewRoute =
  AuthenticatedEntitiesNewRouteImport.update({
    id: '/entities/new',
    path: '/entities/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNNotificationIdRoute =
  AuthenticatedNNotificationIdRouteImport.update({
    id: '/n/$notificationId',
    path: '/n/$notificationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformAuditRoute =
  AuthenticatedPlatformAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformBreachPlaybookRoute =
  AuthenticatedPlatformBreachPlaybookRouteImport.update({
    id: '/breach-playbook',
    path: '/breach-playbook',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformBreakglassRoute =
  AuthenticatedPlatformBreakglassRouteImport.update({
    id: '/breakglass',
    path: '/breakglass',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformContentRoute =
  AuthenticatedPlatformContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformDsrRoute =
  AuthenticatedPlatformDsrRouteImport.update({
    id: '/dsr',
    path: '/dsr',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformEntitiesRoute =
  AuthenticatedPlatformEntitiesRouteImport.update({
    id: '/entities',
    path: '/entities',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformEscalationsRoute =
  AuthenticatedPlatformEscalationsRouteImport.update({
    id: '/escalations',
    path: '/escalations',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformFlagsRoute =
  AuthenticatedPlatformFlagsRouteImport.update({
    id: '/flags',
    path: '/flags',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformIncidentsRoute =
  AuthenticatedPlatformIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformIntegrationsRoute =
  AuthenticatedPlatformIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformLegalRoute =
  AuthenticatedPlatformLegalRouteImport.update({
    id: '/legal',
    path: '/legal',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformPrivacyRoute =
  AuthenticatedPlatformPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformQueueRoute =
  AuthenticatedPlatformQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformReportTemplatesRoute =
  AuthenticatedPlatformReportTemplatesRouteImport.update({
    id: '/report-templates',
    path: '/report-templates',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformRequestsRoute =
  AuthenticatedPlatformRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformSlaRoute =
  AuthenticatedPlatformSlaRouteImport.update({
    id: '/sla',
    path: '/sla',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformStaffRoute =
  AuthenticatedPlatformStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformStudioRoute =
  AuthenticatedPlatformStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformUsersRoute =
  AuthenticatedPlatformUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsRequestIdRoute =
  AuthenticatedRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsMessagingRoute =
  AuthenticatedSettingsMessagingRouteImport.update({
    id: '/settings/messaging',
    path: '/settings/messaging',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPrivacyRoute =
  AuthenticatedSettingsPrivacyRouteImport.update({
    id: '/settings/privacy',
    path: '/settings/privacy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesEntityIdIndexRoute =
  AuthenticatedEntitiesEntityIdIndexRouteImport.update({
    id: '/entities/$entityId/',
    path: '/entities/$entityId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesEntityIdInvitationsRoute =
  AuthenticatedEntitiesEntityIdInvitationsRouteImport.update({
    id: '/entities/$entityId/invitations',
    path: '/entities/$entityId/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesEntityIdPublicProfileRoute =
  AuthenticatedEntitiesEntityIdPublicProfileRouteImport.update({
    id: '/entities/$entityId/public-profile',
    path: '/entities/$entityId/public-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesEntityIdReportTemplatesRoute =
  AuthenticatedEntitiesEntityIdReportTemplatesRouteImport.update({
    id: '/entities/$entityId/report-templates',
    path: '/entities/$entityId/report-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesEntityIdTeamRoute =
  AuthenticatedEntitiesEntityIdTeamRouteImport.update({
    id: '/entities/$entityId/team',
    path: '/entities/$entityId/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformEntityEntityIdRoute =
  AuthenticatedPlatformEntityEntityIdRouteImport.update({
    id: '/entity/$entityId',
    path: '/entity/$entityId',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformUserUserIdRoute =
  AuthenticatedPlatformUserUserIdRouteImport.update({
    id: '/user/$userId',
    path: '/user/$userId',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdClosureRoute =
  AuthenticatedProjectsProjectIdClosureRouteImport.update({
    id: '/projects/$projectId/closure',
    path: '/projects/$projectId/closure',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdContractsRoute =
  AuthenticatedProjectsProjectIdContractsRouteImport.update({
    id: '/projects/$projectId/contracts',
    path: '/projects/$projectId/contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdDrawingsRoute =
  AuthenticatedProjectsProjectIdDrawingsRouteImport.update({
    id: '/projects/$projectId/drawings',
    path: '/projects/$projectId/drawings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdDurationsRoute =
  AuthenticatedProjectsProjectIdDurationsRouteImport.update({
    id: '/projects/$projectId/durations',
    path: '/projects/$projectId/durations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdFinanceRoute =
  AuthenticatedProjectsProjectIdFinanceRouteImport.update({
    id: '/projects/$projectId/finance',
    path: '/projects/$projectId/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdMarketingRoute =
  AuthenticatedProjectsProjectIdMarketingRouteImport.update({
    id: '/projects/$projectId/marketing',
    path: '/projects/$projectId/marketing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdMediaRoute =
  AuthenticatedProjectsProjectIdMediaRouteImport.update({
    id: '/projects/$projectId/media',
    path: '/projects/$projectId/media',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPartiesRoute =
  AuthenticatedProjectsProjectIdPartiesRouteImport.update({
    id: '/projects/$projectId/parties',
    path: '/projects/$projectId/parties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdReportsRoute =
  AuthenticatedProjectsProjectIdReportsRouteImport.update({
    id: '/projects/$projectId/reports',
    path: '/projects/$projectId/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRequestsRoute =
  AuthenticatedProjectsProjectIdRequestsRouteImport.update({
    id: '/projects/$projectId/requests',
    path: '/projects/$projectId/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdServicesRoute =
  AuthenticatedProjectsProjectIdServicesRouteImport.update({
    id: '/projects/$projectId/services',
    path: '/projects/$projectId/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdStagesRoute =
  AuthenticatedProjectsProjectIdStagesRouteImport.update({
    id: '/projects/$projectId/stages',
    path: '/projects/$projectId/stages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdTeamRoute =
  AuthenticatedProjectsProjectIdTeamRouteImport.update({
    id: '/projects/$projectId/team',
    path: '/projects/$projectId/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdVisitsRoute =
  AuthenticatedProjectsProjectIdVisitsRouteImport.update({
    id: '/projects/$projectId/visits',
    path: '/projects/$projectId/visits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdWarrantiesRoute =
  AuthenticatedProjectsProjectIdWarrantiesRouteImport.update({
    id: '/projects/$projectId/warranties',
    path: '/projects/$projectId/warranties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronDurationScanRoute =
  ApiPublicCronDurationScanRouteImport.update({
    id: '/api/public/cron/duration-scan',
    path: '/api/public/cron/duration-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMailCallbackRoute = ApiPublicMailCallbackRouteImport.update({
  id: '/api/public/mail/callback',
  path: '/api/public/mail/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEntitiesEntityIdTemplateImportsImportIdRoute =
  AuthenticatedEntitiesEntityIdTemplateImportsImportIdRouteImport.update({
    id: '/entities/$entityId/template-imports/$importId',
    path: '/entities/$entityId/template-imports/$importId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/select-account': typeof SelectAccountRoute
  '/verify-appointment': typeof VerifyAppointmentRoute
  '/verify-file': typeof VerifyFileRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/correspondence': typeof AuthenticatedCorrespondenceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/e/$slug': typeof ESlugRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/ip': typeof LegalIpRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/m/$token': typeof MTokenRoute
  '/mp/$token': typeof MpTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/report-templates': typeof AuthenticatedAdminReportTemplatesRoute
  '/documents/analyze': typeof AuthenticatedDocumentsAnalyzeRoute
  '/drawings/$drawingId': typeof AuthenticatedDrawingsDrawingIdRoute
  '/entities/new': typeof AuthenticatedEntitiesNewRoute
  '/n/$notificationId': typeof AuthenticatedNNotificationIdRoute
  '/platform/audit': typeof AuthenticatedPlatformAuditRoute
  '/platform/breach-playbook': typeof AuthenticatedPlatformBreachPlaybookRoute
  '/platform/breakglass': typeof AuthenticatedPlatformBreakglassRoute
  '/platform/content': typeof AuthenticatedPlatformContentRoute
  '/platform/dsr': typeof AuthenticatedPlatformDsrRoute
  '/platform/entities': typeof AuthenticatedPlatformEntitiesRoute
  '/platform/escalations': typeof AuthenticatedPlatformEscalationsRoute
  '/platform/flags': typeof AuthenticatedPlatformFlagsRoute
  '/platform/incidents': typeof AuthenticatedPlatformIncidentsRoute
  '/platform/integrations': typeof AuthenticatedPlatformIntegrationsRoute
  '/platform/legal': typeof AuthenticatedPlatformLegalRoute
  '/platform/privacy': typeof AuthenticatedPlatformPrivacyRoute
  '/platform/queue': typeof AuthenticatedPlatformQueueRoute
  '/platform/report-templates': typeof AuthenticatedPlatformReportTemplatesRoute
  '/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/platform/sla': typeof AuthenticatedPlatformSlaRoute
  '/platform/staff': typeof AuthenticatedPlatformStaffRoute
  '/platform/studio': typeof AuthenticatedPlatformStudioRoute
  '/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/settings/messaging': typeof AuthenticatedSettingsMessagingRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/entities/$entityId/invitations': typeof AuthenticatedEntitiesEntityIdInvitationsRoute
  '/entities/$entityId/public-profile': typeof AuthenticatedEntitiesEntityIdPublicProfileRoute
  '/entities/$entityId/report-templates': typeof AuthenticatedEntitiesEntityIdReportTemplatesRoute
  '/entities/$entityId/team': typeof AuthenticatedEntitiesEntityIdTeamRoute
  '/platform/entity/$entityId': typeof AuthenticatedPlatformEntityEntityIdRoute
  '/platform/user/$userId': typeof AuthenticatedPlatformUserUserIdRoute
  '/projects/$projectId/closure': typeof AuthenticatedProjectsProjectIdClosureRoute
  '/projects/$projectId/contracts': typeof AuthenticatedProjectsProjectIdContractsRoute
  '/projects/$projectId/drawings': typeof AuthenticatedProjectsProjectIdDrawingsRoute
  '/projects/$projectId/durations': typeof AuthenticatedProjectsProjectIdDurationsRoute
  '/projects/$projectId/finance': typeof AuthenticatedProjectsProjectIdFinanceRoute
  '/projects/$projectId/marketing': typeof AuthenticatedProjectsProjectIdMarketingRoute
  '/projects/$projectId/media': typeof AuthenticatedProjectsProjectIdMediaRoute
  '/projects/$projectId/parties': typeof AuthenticatedProjectsProjectIdPartiesRoute
  '/projects/$projectId/reports': typeof AuthenticatedProjectsProjectIdReportsRoute
  '/projects/$projectId/requests': typeof AuthenticatedProjectsProjectIdRequestsRoute
  '/projects/$projectId/services': typeof AuthenticatedProjectsProjectIdServicesRoute
  '/projects/$projectId/stages': typeof AuthenticatedProjectsProjectIdStagesRoute
  '/projects/$projectId/team': typeof AuthenticatedProjectsProjectIdTeamRoute
  '/projects/$projectId/visits': typeof AuthenticatedProjectsProjectIdVisitsRoute
  '/projects/$projectId/warranties': typeof AuthenticatedProjectsProjectIdWarrantiesRoute
  '/api/public/cron/duration-scan': typeof ApiPublicCronDurationScanRoute
  '/api/public/mail/callback': typeof ApiPublicMailCallbackRoute
  '/entities/$entityId/': typeof AuthenticatedEntitiesEntityIdIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/entities/$entityId/template-imports/$importId': typeof AuthenticatedEntitiesEntityIdTemplateImportsImportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select-account': typeof SelectAccountRoute
  '/verify-appointment': typeof VerifyAppointmentRoute
  '/verify-file': typeof VerifyFileRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/correspondence': typeof AuthenticatedCorrespondenceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/e/$slug': typeof ESlugRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/ip': typeof LegalIpRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/m/$token': typeof MTokenRoute
  '/mp/$token': typeof MpTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/auth': typeof AuthIndexRoute
  '/admin/report-templates': typeof AuthenticatedAdminReportTemplatesRoute
  '/documents/analyze': typeof AuthenticatedDocumentsAnalyzeRoute
  '/drawings/$drawingId': typeof AuthenticatedDrawingsDrawingIdRoute
  '/entities/new': typeof AuthenticatedEntitiesNewRoute
  '/n/$notificationId': typeof AuthenticatedNNotificationIdRoute
  '/platform/audit': typeof AuthenticatedPlatformAuditRoute
  '/platform/breach-playbook': typeof AuthenticatedPlatformBreachPlaybookRoute
  '/platform/breakglass': typeof AuthenticatedPlatformBreakglassRoute
  '/platform/content': typeof AuthenticatedPlatformContentRoute
  '/platform/dsr': typeof AuthenticatedPlatformDsrRoute
  '/platform/entities': typeof AuthenticatedPlatformEntitiesRoute
  '/platform/escalations': typeof AuthenticatedPlatformEscalationsRoute
  '/platform/flags': typeof AuthenticatedPlatformFlagsRoute
  '/platform/incidents': typeof AuthenticatedPlatformIncidentsRoute
  '/platform/integrations': typeof AuthenticatedPlatformIntegrationsRoute
  '/platform/legal': typeof AuthenticatedPlatformLegalRoute
  '/platform/privacy': typeof AuthenticatedPlatformPrivacyRoute
  '/platform/queue': typeof AuthenticatedPlatformQueueRoute
  '/platform/report-templates': typeof AuthenticatedPlatformReportTemplatesRoute
  '/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/platform/sla': typeof AuthenticatedPlatformSlaRoute
  '/platform/staff': typeof AuthenticatedPlatformStaffRoute
  '/platform/studio': typeof AuthenticatedPlatformStudioRoute
  '/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/settings/messaging': typeof AuthenticatedSettingsMessagingRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/entities/$entityId/invitations': typeof AuthenticatedEntitiesEntityIdInvitationsRoute
  '/entities/$entityId/public-profile': typeof AuthenticatedEntitiesEntityIdPublicProfileRoute
  '/entities/$entityId/report-templates': typeof AuthenticatedEntitiesEntityIdReportTemplatesRoute
  '/entities/$entityId/team': typeof AuthenticatedEntitiesEntityIdTeamRoute
  '/platform/entity/$entityId': typeof AuthenticatedPlatformEntityEntityIdRoute
  '/platform/user/$userId': typeof AuthenticatedPlatformUserUserIdRoute
  '/projects/$projectId/closure': typeof AuthenticatedProjectsProjectIdClosureRoute
  '/projects/$projectId/contracts': typeof AuthenticatedProjectsProjectIdContractsRoute
  '/projects/$projectId/drawings': typeof AuthenticatedProjectsProjectIdDrawingsRoute
  '/projects/$projectId/durations': typeof AuthenticatedProjectsProjectIdDurationsRoute
  '/projects/$projectId/finance': typeof AuthenticatedProjectsProjectIdFinanceRoute
  '/projects/$projectId/marketing': typeof AuthenticatedProjectsProjectIdMarketingRoute
  '/projects/$projectId/media': typeof AuthenticatedProjectsProjectIdMediaRoute
  '/projects/$projectId/parties': typeof AuthenticatedProjectsProjectIdPartiesRoute
  '/projects/$projectId/reports': typeof AuthenticatedProjectsProjectIdReportsRoute
  '/projects/$projectId/requests': typeof AuthenticatedProjectsProjectIdRequestsRoute
  '/projects/$projectId/services': typeof AuthenticatedProjectsProjectIdServicesRoute
  '/projects/$projectId/stages': typeof AuthenticatedProjectsProjectIdStagesRoute
  '/projects/$projectId/team': typeof AuthenticatedProjectsProjectIdTeamRoute
  '/projects/$projectId/visits': typeof AuthenticatedProjectsProjectIdVisitsRoute
  '/projects/$projectId/warranties': typeof AuthenticatedProjectsProjectIdWarrantiesRoute
  '/api/public/cron/duration-scan': typeof ApiPublicCronDurationScanRoute
  '/api/public/mail/callback': typeof ApiPublicMailCallbackRoute
  '/entities/$entityId': typeof AuthenticatedEntitiesEntityIdIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/entities/$entityId/template-imports/$importId': typeof AuthenticatedEntitiesEntityIdTemplateImportsImportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/select-account': typeof SelectAccountRoute
  '/verify-appointment': typeof VerifyAppointmentRoute
  '/verify-file': typeof VerifyFileRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/correspondence': typeof AuthenticatedCorrespondenceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/e/$slug': typeof ESlugRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/ip': typeof LegalIpRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/m/$token': typeof MTokenRoute
  '/mp/$token': typeof MpTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/admin/report-templates': typeof AuthenticatedAdminReportTemplatesRoute
  '/_authenticated/documents/analyze': typeof AuthenticatedDocumentsAnalyzeRoute
  '/_authenticated/drawings/$drawingId': typeof AuthenticatedDrawingsDrawingIdRoute
  '/_authenticated/entities/new': typeof AuthenticatedEntitiesNewRoute
  '/_authenticated/n/$notificationId': typeof AuthenticatedNNotificationIdRoute
  '/_authenticated/platform/audit': typeof AuthenticatedPlatformAuditRoute
  '/_authenticated/platform/breach-playbook': typeof AuthenticatedPlatformBreachPlaybookRoute
  '/_authenticated/platform/breakglass': typeof AuthenticatedPlatformBreakglassRoute
  '/_authenticated/platform/content': typeof AuthenticatedPlatformContentRoute
  '/_authenticated/platform/dsr': typeof AuthenticatedPlatformDsrRoute
  '/_authenticated/platform/entities': typeof AuthenticatedPlatformEntitiesRoute
  '/_authenticated/platform/escalations': typeof AuthenticatedPlatformEscalationsRoute
  '/_authenticated/platform/flags': typeof AuthenticatedPlatformFlagsRoute
  '/_authenticated/platform/incidents': typeof AuthenticatedPlatformIncidentsRoute
  '/_authenticated/platform/integrations': typeof AuthenticatedPlatformIntegrationsRoute
  '/_authenticated/platform/legal': typeof AuthenticatedPlatformLegalRoute
  '/_authenticated/platform/privacy': typeof AuthenticatedPlatformPrivacyRoute
  '/_authenticated/platform/queue': typeof AuthenticatedPlatformQueueRoute
  '/_authenticated/platform/report-templates': typeof AuthenticatedPlatformReportTemplatesRoute
  '/_authenticated/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/_authenticated/platform/sla': typeof AuthenticatedPlatformSlaRoute
  '/_authenticated/platform/staff': typeof AuthenticatedPlatformStaffRoute
  '/_authenticated/platform/studio': typeof AuthenticatedPlatformStudioRoute
  '/_authenticated/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/_authenticated/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/_authenticated/settings/messaging': typeof AuthenticatedSettingsMessagingRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/entities/$entityId/invitations': typeof AuthenticatedEntitiesEntityIdInvitationsRoute
  '/_authenticated/entities/$entityId/public-profile': typeof AuthenticatedEntitiesEntityIdPublicProfileRoute
  '/_authenticated/entities/$entityId/report-templates': typeof AuthenticatedEntitiesEntityIdReportTemplatesRoute
  '/_authenticated/entities/$entityId/team': typeof AuthenticatedEntitiesEntityIdTeamRoute
  '/_authenticated/platform/entity/$entityId': typeof AuthenticatedPlatformEntityEntityIdRoute
  '/_authenticated/platform/user/$userId': typeof AuthenticatedPlatformUserUserIdRoute
  '/_authenticated/projects/$projectId/closure': typeof AuthenticatedProjectsProjectIdClosureRoute
  '/_authenticated/projects/$projectId/contracts': typeof AuthenticatedProjectsProjectIdContractsRoute
  '/_authenticated/projects/$projectId/drawings': typeof AuthenticatedProjectsProjectIdDrawingsRoute
  '/_authenticated/projects/$projectId/durations': typeof AuthenticatedProjectsProjectIdDurationsRoute
  '/_authenticated/projects/$projectId/finance': typeof AuthenticatedProjectsProjectIdFinanceRoute
  '/_authenticated/projects/$projectId/marketing': typeof AuthenticatedProjectsProjectIdMarketingRoute
  '/_authenticated/projects/$projectId/media': typeof AuthenticatedProjectsProjectIdMediaRoute
  '/_authenticated/projects/$projectId/parties': typeof AuthenticatedProjectsProjectIdPartiesRoute
  '/_authenticated/projects/$projectId/reports': typeof AuthenticatedProjectsProjectIdReportsRoute
  '/_authenticated/projects/$projectId/requests': typeof AuthenticatedProjectsProjectIdRequestsRoute
  '/_authenticated/projects/$projectId/services': typeof AuthenticatedProjectsProjectIdServicesRoute
  '/_authenticated/projects/$projectId/stages': typeof AuthenticatedProjectsProjectIdStagesRoute
  '/_authenticated/projects/$projectId/team': typeof AuthenticatedProjectsProjectIdTeamRoute
  '/_authenticated/projects/$projectId/visits': typeof AuthenticatedProjectsProjectIdVisitsRoute
  '/_authenticated/projects/$projectId/warranties': typeof AuthenticatedProjectsProjectIdWarrantiesRoute
  '/api/public/cron/duration-scan': typeof ApiPublicCronDurationScanRoute
  '/api/public/mail/callback': typeof ApiPublicMailCallbackRoute
  '/_authenticated/entities/$entityId/': typeof AuthenticatedEntitiesEntityIdIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/entities/$entityId/template-imports/$importId': typeof AuthenticatedEntitiesEntityIdTemplateImportsImportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/select-account'
    | '/verify-appointment'
    | '/verify-file'
    | '/appointments'
    | '/archive'
    | '/calls'
    | '/correspondence'
    | '/dashboard'
    | '/deals'
    | '/marketing'
    | '/marketplace'
    | '/network'
    | '/notifications'
    | '/platform'
    | '/profile'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/e/$slug'
    | '/invite/accept'
    | '/legal/complaints'
    | '/legal/ip'
    | '/legal/privacy'
    | '/legal/terms'
    | '/m/$token'
    | '/mp/$token'
    | '/verify/$token'
    | '/auth/'
    | '/admin/report-templates'
    | '/documents/analyze'
    | '/drawings/$drawingId'
    | '/entities/new'
    | '/n/$notificationId'
    | '/platform/audit'
    | '/platform/breach-playbook'
    | '/platform/breakglass'
    | '/platform/content'
    | '/platform/dsr'
    | '/platform/entities'
    | '/platform/escalations'
    | '/platform/flags'
    | '/platform/incidents'
    | '/platform/integrations'
    | '/platform/legal'
    | '/platform/privacy'
    | '/platform/queue'
    | '/platform/report-templates'
    | '/platform/requests'
    | '/platform/sla'
    | '/platform/staff'
    | '/platform/studio'
    | '/platform/users'
    | '/projects/new'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/reports/$reportId'
    | '/requests/$requestId'
    | '/settings/messaging'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/security'
    | '/documents/'
    | '/platform/'
    | '/projects/'
    | '/properties/'
    | '/requests/'
    | '/entities/$entityId/invitations'
    | '/entities/$entityId/public-profile'
    | '/entities/$entityId/report-templates'
    | '/entities/$entityId/team'
    | '/platform/entity/$entityId'
    | '/platform/user/$userId'
    | '/projects/$projectId/closure'
    | '/projects/$projectId/contracts'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/durations'
    | '/projects/$projectId/finance'
    | '/projects/$projectId/marketing'
    | '/projects/$projectId/media'
    | '/projects/$projectId/parties'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/requests'
    | '/projects/$projectId/services'
    | '/projects/$projectId/stages'
    | '/projects/$projectId/team'
    | '/projects/$projectId/visits'
    | '/projects/$projectId/warranties'
    | '/api/public/cron/duration-scan'
    | '/api/public/mail/callback'
    | '/entities/$entityId/'
    | '/projects/$projectId/'
    | '/entities/$entityId/template-imports/$importId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/select-account'
    | '/verify-appointment'
    | '/verify-file'
    | '/appointments'
    | '/archive'
    | '/calls'
    | '/correspondence'
    | '/dashboard'
    | '/deals'
    | '/marketing'
    | '/marketplace'
    | '/network'
    | '/notifications'
    | '/profile'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/e/$slug'
    | '/invite/accept'
    | '/legal/complaints'
    | '/legal/ip'
    | '/legal/privacy'
    | '/legal/terms'
    | '/m/$token'
    | '/mp/$token'
    | '/verify/$token'
    | '/auth'
    | '/admin/report-templates'
    | '/documents/analyze'
    | '/drawings/$drawingId'
    | '/entities/new'
    | '/n/$notificationId'
    | '/platform/audit'
    | '/platform/breach-playbook'
    | '/platform/breakglass'
    | '/platform/content'
    | '/platform/dsr'
    | '/platform/entities'
    | '/platform/escalations'
    | '/platform/flags'
    | '/platform/incidents'
    | '/platform/integrations'
    | '/platform/legal'
    | '/platform/privacy'
    | '/platform/queue'
    | '/platform/report-templates'
    | '/platform/requests'
    | '/platform/sla'
    | '/platform/staff'
    | '/platform/studio'
    | '/platform/users'
    | '/projects/new'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/reports/$reportId'
    | '/requests/$requestId'
    | '/settings/messaging'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/security'
    | '/documents'
    | '/platform'
    | '/projects'
    | '/properties'
    | '/requests'
    | '/entities/$entityId/invitations'
    | '/entities/$entityId/public-profile'
    | '/entities/$entityId/report-templates'
    | '/entities/$entityId/team'
    | '/platform/entity/$entityId'
    | '/platform/user/$userId'
    | '/projects/$projectId/closure'
    | '/projects/$projectId/contracts'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/durations'
    | '/projects/$projectId/finance'
    | '/projects/$projectId/marketing'
    | '/projects/$projectId/media'
    | '/projects/$projectId/parties'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/requests'
    | '/projects/$projectId/services'
    | '/projects/$projectId/stages'
    | '/projects/$projectId/team'
    | '/projects/$projectId/visits'
    | '/projects/$projectId/warranties'
    | '/api/public/cron/duration-scan'
    | '/api/public/mail/callback'
    | '/entities/$entityId'
    | '/projects/$projectId'
    | '/entities/$entityId/template-imports/$importId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/select-account'
    | '/verify-appointment'
    | '/verify-file'
    | '/_authenticated/appointments'
    | '/_authenticated/archive'
    | '/_authenticated/calls'
    | '/_authenticated/correspondence'
    | '/_authenticated/dashboard'
    | '/_authenticated/deals'
    | '/_authenticated/marketing'
    | '/_authenticated/marketplace'
    | '/_authenticated/network'
    | '/_authenticated/notifications'
    | '/_authenticated/platform'
    | '/_authenticated/profile'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/e/$slug'
    | '/invite/accept'
    | '/legal/complaints'
    | '/legal/ip'
    | '/legal/privacy'
    | '/legal/terms'
    | '/m/$token'
    | '/mp/$token'
    | '/verify/$token'
    | '/auth/'
    | '/_authenticated/admin/report-templates'
    | '/_authenticated/documents/analyze'
    | '/_authenticated/drawings/$drawingId'
    | '/_authenticated/entities/new'
    | '/_authenticated/n/$notificationId'
    | '/_authenticated/platform/audit'
    | '/_authenticated/platform/breach-playbook'
    | '/_authenticated/platform/breakglass'
    | '/_authenticated/platform/content'
    | '/_authenticated/platform/dsr'
    | '/_authenticated/platform/entities'
    | '/_authenticated/platform/escalations'
    | '/_authenticated/platform/flags'
    | '/_authenticated/platform/incidents'
    | '/_authenticated/platform/integrations'
    | '/_authenticated/platform/legal'
    | '/_authenticated/platform/privacy'
    | '/_authenticated/platform/queue'
    | '/_authenticated/platform/report-templates'
    | '/_authenticated/platform/requests'
    | '/_authenticated/platform/sla'
    | '/_authenticated/platform/staff'
    | '/_authenticated/platform/studio'
    | '/_authenticated/platform/users'
    | '/_authenticated/projects/new'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/properties/new'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/requests/$requestId'
    | '/_authenticated/settings/messaging'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/privacy'
    | '/_authenticated/settings/security'
    | '/_authenticated/documents/'
    | '/_authenticated/platform/'
    | '/_authenticated/projects/'
    | '/_authenticated/properties/'
    | '/_authenticated/requests/'
    | '/_authenticated/entities/$entityId/invitations'
    | '/_authenticated/entities/$entityId/public-profile'
    | '/_authenticated/entities/$entityId/report-templates'
    | '/_authenticated/entities/$entityId/team'
    | '/_authenticated/platform/entity/$entityId'
    | '/_authenticated/platform/user/$userId'
    | '/_authenticated/projects/$projectId/closure'
    | '/_authenticated/projects/$projectId/contracts'
    | '/_authenticated/projects/$projectId/drawings'
    | '/_authenticated/projects/$projectId/durations'
    | '/_authenticated/projects/$projectId/finance'
    | '/_authenticated/projects/$projectId/marketing'
    | '/_authenticated/projects/$projectId/media'
    | '/_authenticated/projects/$projectId/parties'
    | '/_authenticated/projects/$projectId/reports'
    | '/_authenticated/projects/$projectId/requests'
    | '/_authenticated/projects/$projectId/services'
    | '/_authenticated/projects/$projectId/stages'
    | '/_authenticated/projects/$projectId/team'
    | '/_authenticated/projects/$projectId/visits'
    | '/_authenticated/projects/$projectId/warranties'
    | '/api/public/cron/duration-scan'
    | '/api/public/mail/callback'
    | '/_authenticated/entities/$entityId/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/entities/$entityId/template-imports/$importId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SelectAccountRoute: typeof SelectAccountRoute
  VerifyAppointmentRoute: typeof VerifyAppointmentRoute
  VerifyFileRoute: typeof VerifyFileRoute
  ESlugRoute: typeof ESlugRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  LegalComplaintsRoute: typeof LegalComplaintsRoute
  LegalIpRoute: typeof LegalIpRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MTokenRoute: typeof MTokenRoute
  MpTokenRoute: typeof MpTokenRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  ApiPublicCronDurationScanRoute: typeof ApiPublicCronDurationScanRoute
  ApiPublicMailCallbackRoute: typeof ApiPublicMailCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-account': {
      id: '/select-account'
      path: '/select-account'
      fullPath: '/select-account'
      preLoaderRoute: typeof SelectAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-appointment': {
      id: '/verify-appointment'
      path: '/verify-appointment'
      fullPath: '/verify-appointment'
      preLoaderRoute: typeof VerifyAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-file': {
      id: '/verify-file'
      path: '/verify-file'
      fullPath: '/verify-file'
      preLoaderRoute: typeof VerifyFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/correspondence': {
      id: '/_authenticated/correspondence'
      path: '/correspondence'
      fullPath: '/correspondence'
      preLoaderRoute: typeof AuthenticatedCorrespondenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/complaints': {
      id: '/legal/complaints'
      path: '/legal/complaints'
      fullPath: '/legal/complaints'
      preLoaderRoute: typeof LegalComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/ip': {
      id: '/legal/ip'
      path: '/legal/ip'
      fullPath: '/legal/ip'
      preLoaderRoute: typeof LegalIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$token': {
      id: '/m/$token'
      path: '/m/$token'
      fullPath: '/m/$token'
      preLoaderRoute: typeof MTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mp/$token': {
      id: '/mp/$token'
      path: '/mp/$token'
      fullPath: '/mp/$token'
      preLoaderRoute: typeof MpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/report-templates': {
      id: '/_authenticated/admin/report-templates'
      path: '/admin/report-templates'
      fullPath: '/admin/report-templates'
      preLoaderRoute: typeof AuthenticatedAdminReportTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/analyze': {
      id: '/_authenticated/documents/analyze'
      path: '/documents/analyze'
      fullPath: '/documents/analyze'
      preLoaderRoute: typeof AuthenticatedDocumentsAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drawings/$drawingId': {
      id: '/_authenticated/drawings/$drawingId'
      path: '/drawings/$drawingId'
      fullPath: '/drawings/$drawingId'
      preLoaderRoute: typeof AuthenticatedDrawingsDrawingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/new': {
      id: '/_authenticated/entities/new'
      path: '/entities/new'
      fullPath: '/entities/new'
      preLoaderRoute: typeof AuthenticatedEntitiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/n/$notificationId': {
      id: '/_authenticated/n/$notificationId'
      path: '/n/$notificationId'
      fullPath: '/n/$notificationId'
      preLoaderRoute: typeof AuthenticatedNNotificationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/audit': {
      id: '/_authenticated/platform/audit'
      path: '/audit'
      fullPath: '/platform/audit'
      preLoaderRoute: typeof AuthenticatedPlatformAuditRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/breach-playbook': {
      id: '/_authenticated/platform/breach-playbook'
      path: '/breach-playbook'
      fullPath: '/platform/breach-playbook'
      preLoaderRoute: typeof AuthenticatedPlatformBreachPlaybookRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/breakglass': {
      id: '/_authenticated/platform/breakglass'
      path: '/breakglass'
      fullPath: '/platform/breakglass'
      preLoaderRoute: typeof AuthenticatedPlatformBreakglassRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/content': {
      id: '/_authenticated/platform/content'
      path: '/content'
      fullPath: '/platform/content'
      preLoaderRoute: typeof AuthenticatedPlatformContentRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/dsr': {
      id: '/_authenticated/platform/dsr'
      path: '/dsr'
      fullPath: '/platform/dsr'
      preLoaderRoute: typeof AuthenticatedPlatformDsrRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/entities': {
      id: '/_authenticated/platform/entities'
      path: '/entities'
      fullPath: '/platform/entities'
      preLoaderRoute: typeof AuthenticatedPlatformEntitiesRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/escalations': {
      id: '/_authenticated/platform/escalations'
      path: '/escalations'
      fullPath: '/platform/escalations'
      preLoaderRoute: typeof AuthenticatedPlatformEscalationsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/flags': {
      id: '/_authenticated/platform/flags'
      path: '/flags'
      fullPath: '/platform/flags'
      preLoaderRoute: typeof AuthenticatedPlatformFlagsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/incidents': {
      id: '/_authenticated/platform/incidents'
      path: '/incidents'
      fullPath: '/platform/incidents'
      preLoaderRoute: typeof AuthenticatedPlatformIncidentsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/integrations': {
      id: '/_authenticated/platform/integrations'
      path: '/integrations'
      fullPath: '/platform/integrations'
      preLoaderRoute: typeof AuthenticatedPlatformIntegrationsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/legal': {
      id: '/_authenticated/platform/legal'
      path: '/legal'
      fullPath: '/platform/legal'
      preLoaderRoute: typeof AuthenticatedPlatformLegalRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/privacy': {
      id: '/_authenticated/platform/privacy'
      path: '/privacy'
      fullPath: '/platform/privacy'
      preLoaderRoute: typeof AuthenticatedPlatformPrivacyRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/queue': {
      id: '/_authenticated/platform/queue'
      path: '/queue'
      fullPath: '/platform/queue'
      preLoaderRoute: typeof AuthenticatedPlatformQueueRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/report-templates': {
      id: '/_authenticated/platform/report-templates'
      path: '/report-templates'
      fullPath: '/platform/report-templates'
      preLoaderRoute: typeof AuthenticatedPlatformReportTemplatesRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/requests': {
      id: '/_authenticated/platform/requests'
      path: '/requests'
      fullPath: '/platform/requests'
      preLoaderRoute: typeof AuthenticatedPlatformRequestsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/sla': {
      id: '/_authenticated/platform/sla'
      path: '/sla'
      fullPath: '/platform/sla'
      preLoaderRoute: typeof AuthenticatedPlatformSlaRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/staff': {
      id: '/_authenticated/platform/staff'
      path: '/staff'
      fullPath: '/platform/staff'
      preLoaderRoute: typeof AuthenticatedPlatformStaffRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/studio': {
      id: '/_authenticated/platform/studio'
      path: '/studio'
      fullPath: '/platform/studio'
      preLoaderRoute: typeof AuthenticatedPlatformStudioRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/users': {
      id: '/_authenticated/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof AuthenticatedPlatformUsersRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/$requestId': {
      id: '/_authenticated/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/messaging': {
      id: '/_authenticated/settings/messaging'
      path: '/settings/messaging'
      fullPath: '/settings/messaging'
      preLoaderRoute: typeof AuthenticatedSettingsMessagingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/privacy': {
      id: '/_authenticated/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthenticatedSettingsPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/$entityId/': {
      id: '/_authenticated/entities/$entityId/'
      path: '/entities/$entityId'
      fullPath: '/entities/$entityId/'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/$entityId/invitations': {
      id: '/_authenticated/entities/$entityId/invitations'
      path: '/entities/$entityId/invitations'
      fullPath: '/entities/$entityId/invitations'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityIdInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/$entityId/public-profile': {
      id: '/_authenticated/entities/$entityId/public-profile'
      path: '/entities/$entityId/public-profile'
      fullPath: '/entities/$entityId/public-profile'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityIdPublicProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/$entityId/report-templates': {
      id: '/_authenticated/entities/$entityId/report-templates'
      path: '/entities/$entityId/report-templates'
      fullPath: '/entities/$entityId/report-templates'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityIdReportTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/$entityId/team': {
      id: '/_authenticated/entities/$entityId/team'
      path: '/entities/$entityId/team'
      fullPath: '/entities/$entityId/team'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityIdTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/entity/$entityId': {
      id: '/_authenticated/platform/entity/$entityId'
      path: '/entity/$entityId'
      fullPath: '/platform/entity/$entityId'
      preLoaderRoute: typeof AuthenticatedPlatformEntityEntityIdRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/user/$userId': {
      id: '/_authenticated/platform/user/$userId'
      path: '/user/$userId'
      fullPath: '/platform/user/$userId'
      preLoaderRoute: typeof AuthenticatedPlatformUserUserIdRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/closure': {
      id: '/_authenticated/projects/$projectId/closure'
      path: '/projects/$projectId/closure'
      fullPath: '/projects/$projectId/closure'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdClosureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/contracts': {
      id: '/_authenticated/projects/$projectId/contracts'
      path: '/projects/$projectId/contracts'
      fullPath: '/projects/$projectId/contracts'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/drawings': {
      id: '/_authenticated/projects/$projectId/drawings'
      path: '/projects/$projectId/drawings'
      fullPath: '/projects/$projectId/drawings'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDrawingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/durations': {
      id: '/_authenticated/projects/$projectId/durations'
      path: '/projects/$projectId/durations'
      fullPath: '/projects/$projectId/durations'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDurationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/finance': {
      id: '/_authenticated/projects/$projectId/finance'
      path: '/projects/$projectId/finance'
      fullPath: '/projects/$projectId/finance'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/marketing': {
      id: '/_authenticated/projects/$projectId/marketing'
      path: '/projects/$projectId/marketing'
      fullPath: '/projects/$projectId/marketing'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/media': {
      id: '/_authenticated/projects/$projectId/media'
      path: '/projects/$projectId/media'
      fullPath: '/projects/$projectId/media'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/parties': {
      id: '/_authenticated/projects/$projectId/parties'
      path: '/projects/$projectId/parties'
      fullPath: '/projects/$projectId/parties'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPartiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/reports': {
      id: '/_authenticated/projects/$projectId/reports'
      path: '/projects/$projectId/reports'
      fullPath: '/projects/$projectId/reports'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/requests': {
      id: '/_authenticated/projects/$projectId/requests'
      path: '/projects/$projectId/requests'
      fullPath: '/projects/$projectId/requests'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/services': {
      id: '/_authenticated/projects/$projectId/services'
      path: '/projects/$projectId/services'
      fullPath: '/projects/$projectId/services'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/stages': {
      id: '/_authenticated/projects/$projectId/stages'
      path: '/projects/$projectId/stages'
      fullPath: '/projects/$projectId/stages'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdStagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/team': {
      id: '/_authenticated/projects/$projectId/team'
      path: '/projects/$projectId/team'
      fullPath: '/projects/$projectId/team'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/visits': {
      id: '/_authenticated/projects/$projectId/visits'
      path: '/projects/$projectId/visits'
      fullPath: '/projects/$projectId/visits'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/warranties': {
      id: '/_authenticated/projects/$projectId/warranties'
      path: '/projects/$projectId/warranties'
      fullPath: '/projects/$projectId/warranties'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdWarrantiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/duration-scan': {
      id: '/api/public/cron/duration-scan'
      path: '/api/public/cron/duration-scan'
      fullPath: '/api/public/cron/duration-scan'
      preLoaderRoute: typeof ApiPublicCronDurationScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mail/callback': {
      id: '/api/public/mail/callback'
      path: '/api/public/mail/callback'
      fullPath: '/api/public/mail/callback'
      preLoaderRoute: typeof ApiPublicMailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/entities/$entityId/template-imports/$importId': {
      id: '/_authenticated/entities/$entityId/template-imports/$importId'
      path: '/entities/$entityId/template-imports/$importId'
      fullPath: '/entities/$entityId/template-imports/$importId'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityIdTemplateImportsImportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedPlatformRouteChildren {
  AuthenticatedPlatformAuditRoute: typeof AuthenticatedPlatformAuditRoute
  AuthenticatedPlatformBreachPlaybookRoute: typeof AuthenticatedPlatformBreachPlaybookRoute
  AuthenticatedPlatformBreakglassRoute: typeof AuthenticatedPlatformBreakglassRoute
  AuthenticatedPlatformContentRoute: typeof AuthenticatedPlatformContentRoute
  AuthenticatedPlatformDsrRoute: typeof AuthenticatedPlatformDsrRoute
  AuthenticatedPlatformEntitiesRoute: typeof AuthenticatedPlatformEntitiesRoute
  AuthenticatedPlatformEscalationsRoute: typeof AuthenticatedPlatformEscalationsRoute
  AuthenticatedPlatformFlagsRoute: typeof AuthenticatedPlatformFlagsRoute
  AuthenticatedPlatformIncidentsRoute: typeof AuthenticatedPlatformIncidentsRoute
  AuthenticatedPlatformIntegrationsRoute: typeof AuthenticatedPlatformIntegrationsRoute
  AuthenticatedPlatformLegalRoute: typeof AuthenticatedPlatformLegalRoute
  AuthenticatedPlatformPrivacyRoute: typeof AuthenticatedPlatformPrivacyRoute
  AuthenticatedPlatformQueueRoute: typeof AuthenticatedPlatformQueueRoute
  AuthenticatedPlatformReportTemplatesRoute: typeof AuthenticatedPlatformReportTemplatesRoute
  AuthenticatedPlatformRequestsRoute: typeof AuthenticatedPlatformRequestsRoute
  AuthenticatedPlatformSlaRoute: typeof AuthenticatedPlatformSlaRoute
  AuthenticatedPlatformStaffRoute: typeof AuthenticatedPlatformStaffRoute
  AuthenticatedPlatformStudioRoute: typeof AuthenticatedPlatformStudioRoute
  AuthenticatedPlatformUsersRoute: typeof AuthenticatedPlatformUsersRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
  AuthenticatedPlatformEntityEntityIdRoute: typeof AuthenticatedPlatformEntityEntityIdRoute
  AuthenticatedPlatformUserUserIdRoute: typeof AuthenticatedPlatformUserUserIdRoute
}

const AuthenticatedPlatformRouteChildren: AuthenticatedPlatformRouteChildren = {
  AuthenticatedPlatformAuditRoute: AuthenticatedPlatformAuditRoute,
  AuthenticatedPlatformBreachPlaybookRoute:
    AuthenticatedPlatformBreachPlaybookRoute,
  AuthenticatedPlatformBreakglassRoute: AuthenticatedPlatformBreakglassRoute,
  AuthenticatedPlatformContentRoute: AuthenticatedPlatformContentRoute,
  AuthenticatedPlatformDsrRoute: AuthenticatedPlatformDsrRoute,
  AuthenticatedPlatformEntitiesRoute: AuthenticatedPlatformEntitiesRoute,
  AuthenticatedPlatformEscalationsRoute: AuthenticatedPlatformEscalationsRoute,
  AuthenticatedPlatformFlagsRoute: AuthenticatedPlatformFlagsRoute,
  AuthenticatedPlatformIncidentsRoute: AuthenticatedPlatformIncidentsRoute,
  AuthenticatedPlatformIntegrationsRoute:
    AuthenticatedPlatformIntegrationsRoute,
  AuthenticatedPlatformLegalRoute: AuthenticatedPlatformLegalRoute,
  AuthenticatedPlatformPrivacyRoute: AuthenticatedPlatformPrivacyRoute,
  AuthenticatedPlatformQueueRoute: AuthenticatedPlatformQueueRoute,
  AuthenticatedPlatformReportTemplatesRoute:
    AuthenticatedPlatformReportTemplatesRoute,
  AuthenticatedPlatformRequestsRoute: AuthenticatedPlatformRequestsRoute,
  AuthenticatedPlatformSlaRoute: AuthenticatedPlatformSlaRoute,
  AuthenticatedPlatformStaffRoute: AuthenticatedPlatformStaffRoute,
  AuthenticatedPlatformStudioRoute: AuthenticatedPlatformStudioRoute,
  AuthenticatedPlatformUsersRoute: AuthenticatedPlatformUsersRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
  AuthenticatedPlatformEntityEntityIdRoute:
    AuthenticatedPlatformEntityEntityIdRoute,
  AuthenticatedPlatformUserUserIdRoute: AuthenticatedPlatformUserUserIdRoute,
}

const AuthenticatedPlatformRouteWithChildren =
  AuthenticatedPlatformRoute._addFileChildren(
    AuthenticatedPlatformRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedCorrespondenceRoute: typeof AuthenticatedCorrespondenceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminReportTemplatesRoute: typeof AuthenticatedAdminReportTemplatesRoute
  AuthenticatedDocumentsAnalyzeRoute: typeof AuthenticatedDocumentsAnalyzeRoute
  AuthenticatedDrawingsDrawingIdRoute: typeof AuthenticatedDrawingsDrawingIdRoute
  AuthenticatedEntitiesNewRoute: typeof AuthenticatedEntitiesNewRoute
  AuthenticatedNNotificationIdRoute: typeof AuthenticatedNNotificationIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRoute
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
  AuthenticatedRequestsRequestIdRoute: typeof AuthenticatedRequestsRequestIdRoute
  AuthenticatedSettingsMessagingRoute: typeof AuthenticatedSettingsMessagingRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPrivacyRoute: typeof AuthenticatedSettingsPrivacyRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
  AuthenticatedEntitiesEntityIdInvitationsRoute: typeof AuthenticatedEntitiesEntityIdInvitationsRoute
  AuthenticatedEntitiesEntityIdPublicProfileRoute: typeof AuthenticatedEntitiesEntityIdPublicProfileRoute
  AuthenticatedEntitiesEntityIdReportTemplatesRoute: typeof AuthenticatedEntitiesEntityIdReportTemplatesRoute
  AuthenticatedEntitiesEntityIdTeamRoute: typeof AuthenticatedEntitiesEntityIdTeamRoute
  AuthenticatedProjectsProjectIdClosureRoute: typeof AuthenticatedProjectsProjectIdClosureRoute
  AuthenticatedProjectsProjectIdContractsRoute: typeof AuthenticatedProjectsProjectIdContractsRoute
  AuthenticatedProjectsProjectIdDrawingsRoute: typeof AuthenticatedProjectsProjectIdDrawingsRoute
  AuthenticatedProjectsProjectIdDurationsRoute: typeof AuthenticatedProjectsProjectIdDurationsRoute
  AuthenticatedProjectsProjectIdFinanceRoute: typeof AuthenticatedProjectsProjectIdFinanceRoute
  AuthenticatedProjectsProjectIdMarketingRoute: typeof AuthenticatedProjectsProjectIdMarketingRoute
  AuthenticatedProjectsProjectIdMediaRoute: typeof AuthenticatedProjectsProjectIdMediaRoute
  AuthenticatedProjectsProjectIdPartiesRoute: typeof AuthenticatedProjectsProjectIdPartiesRoute
  AuthenticatedProjectsProjectIdReportsRoute: typeof AuthenticatedProjectsProjectIdReportsRoute
  AuthenticatedProjectsProjectIdRequestsRoute: typeof AuthenticatedProjectsProjectIdRequestsRoute
  AuthenticatedProjectsProjectIdServicesRoute: typeof AuthenticatedProjectsProjectIdServicesRoute
  AuthenticatedProjectsProjectIdStagesRoute: typeof AuthenticatedProjectsProjectIdStagesRoute
  AuthenticatedProjectsProjectIdTeamRoute: typeof AuthenticatedProjectsProjectIdTeamRoute
  AuthenticatedProjectsProjectIdVisitsRoute: typeof AuthenticatedProjectsProjectIdVisitsRoute
  AuthenticatedProjectsProjectIdWarrantiesRoute: typeof AuthenticatedProjectsProjectIdWarrantiesRoute
  AuthenticatedEntitiesEntityIdIndexRoute: typeof AuthenticatedEntitiesEntityIdIndexRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedEntitiesEntityIdTemplateImportsImportIdRoute: typeof AuthenticatedEntitiesEntityIdTemplateImportsImportIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedCorrespondenceRoute: AuthenticatedCorrespondenceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminReportTemplatesRoute:
    AuthenticatedAdminReportTemplatesRoute,
  AuthenticatedDocumentsAnalyzeRoute: AuthenticatedDocumentsAnalyzeRoute,
  AuthenticatedDrawingsDrawingIdRoute: AuthenticatedDrawingsDrawingIdRoute,
  AuthenticatedEntitiesNewRoute: AuthenticatedEntitiesNewRoute,
  AuthenticatedNNotificationIdRoute: AuthenticatedNNotificationIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedPropertiesPropertyIdRoute:
    AuthenticatedPropertiesPropertyIdRoute,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
  AuthenticatedRequestsRequestIdRoute: AuthenticatedRequestsRequestIdRoute,
  AuthenticatedSettingsMessagingRoute: AuthenticatedSettingsMessagingRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsPrivacyRoute: AuthenticatedSettingsPrivacyRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
  AuthenticatedEntitiesEntityIdInvitationsRoute:
    AuthenticatedEntitiesEntityIdInvitationsRoute,
  AuthenticatedEntitiesEntityIdPublicProfileRoute:
    AuthenticatedEntitiesEntityIdPublicProfileRoute,
  AuthenticatedEntitiesEntityIdReportTemplatesRoute:
    AuthenticatedEntitiesEntityIdReportTemplatesRoute,
  AuthenticatedEntitiesEntityIdTeamRoute:
    AuthenticatedEntitiesEntityIdTeamRoute,
  AuthenticatedProjectsProjectIdClosureRoute:
    AuthenticatedProjectsProjectIdClosureRoute,
  AuthenticatedProjectsProjectIdContractsRoute:
    AuthenticatedProjectsProjectIdContractsRoute,
  AuthenticatedProjectsProjectIdDrawingsRoute:
    AuthenticatedProjectsProjectIdDrawingsRoute,
  AuthenticatedProjectsProjectIdDurationsRoute:
    AuthenticatedProjectsProjectIdDurationsRoute,
  AuthenticatedProjectsProjectIdFinanceRoute:
    AuthenticatedProjectsProjectIdFinanceRoute,
  AuthenticatedProjectsProjectIdMarketingRoute:
    AuthenticatedProjectsProjectIdMarketingRoute,
  AuthenticatedProjectsProjectIdMediaRoute:
    AuthenticatedProjectsProjectIdMediaRoute,
  AuthenticatedProjectsProjectIdPartiesRoute:
    AuthenticatedProjectsProjectIdPartiesRoute,
  AuthenticatedProjectsProjectIdReportsRoute:
    AuthenticatedProjectsProjectIdReportsRoute,
  AuthenticatedProjectsProjectIdRequestsRoute:
    AuthenticatedProjectsProjectIdRequestsRoute,
  AuthenticatedProjectsProjectIdServicesRoute:
    AuthenticatedProjectsProjectIdServicesRoute,
  AuthenticatedProjectsProjectIdStagesRoute:
    AuthenticatedProjectsProjectIdStagesRoute,
  AuthenticatedProjectsProjectIdTeamRoute:
    AuthenticatedProjectsProjectIdTeamRoute,
  AuthenticatedProjectsProjectIdVisitsRoute:
    AuthenticatedProjectsProjectIdVisitsRoute,
  AuthenticatedProjectsProjectIdWarrantiesRoute:
    AuthenticatedProjectsProjectIdWarrantiesRoute,
  AuthenticatedEntitiesEntityIdIndexRoute:
    AuthenticatedEntitiesEntityIdIndexRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
  AuthenticatedEntitiesEntityIdTemplateImportsImportIdRoute:
    AuthenticatedEntitiesEntityIdTemplateImportsImportIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SelectAccountRoute: SelectAccountRoute,
  VerifyAppointmentRoute: VerifyAppointmentRoute,
  VerifyFileRoute: VerifyFileRoute,
  ESlugRoute: ESlugRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  LegalComplaintsRoute: LegalComplaintsRoute,
  LegalIpRoute: LegalIpRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  MTokenRoute: MTokenRoute,
  MpTokenRoute: MpTokenRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  ApiPublicCronDurationScanRoute: ApiPublicCronDurationScanRoute,
  ApiPublicMailCallbackRoute: ApiPublicMailCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
