/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SelectAccountRouteImport } from './routes/select-account'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as InviteAcceptRouteImport } from './routes/invite.accept'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents.index'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties.index'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties.$propertyId'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated/properties.new'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as AuthenticatedRequestsRequestIdRouteImport } from './routes/_authenticated/requests.$requestId'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedEntitiesEntityIdInvitationsRouteImport } from './routes/_authenticated/entities.$entityId.invitations'
import { Route as AuthenticatedEntitiesEntityIdReportTemplatesRouteImport } from './routes/_authenticated/entities.$entityId.report-templates'
import { Route as AuthenticatedEntitiesEntityIdTeamRouteImport } from './routes/_authenticated/entities.$entityId.team'
import { Route as AuthenticatedProjectsProjectIdContractsRouteImport } from './routes/_authenticated/projects.$projectId.contracts'
import { Route as AuthenticatedProjectsProjectIdPartiesRouteImport } from './routes/_authenticated/projects.$projectId.parties'
import { Route as AuthenticatedProjectsProjectIdReportsRouteImport } from './routes/_authenticated/projects.$projectId.reports'
import { Route as AuthenticatedProjectsProjectIdRequestsRouteImport } from './routes/_authenticated/projects.$projectId.requests'
import { Route as AuthenticatedProjectsProjectIdServicesRouteImport } from './routes/_authenticated/projects.$projectId.services'
import { Route as AuthenticatedProjectsProjectIdStagesRouteImport } from './routes/_authenticated/projects.$projectId.stages'
import { Route as AuthenticatedProjectsProjectIdVisitsRouteImport } from './routes/_authenticated/projects.$projectId.visits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectAccountRoute = SelectAccountRouteImport.update({
  id: '/select-account',
  path: '/select-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsRequestIdRoute =
  AuthenticatedRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesEntityIdInvitationsRoute =
  AuthenticatedEntitiesEntityIdInvitationsRouteImport.update({
    id: '/entities/$entityId/invitations',
    path: '/entities/$entityId/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesEntityIdReportTemplatesRoute =
  AuthenticatedEntitiesEntityIdReportTemplatesRouteImport.update({
    id: '/entities/$entityId/report-templates',
    path: '/entities/$entityId/report-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesEntityIdTeamRoute =
  AuthenticatedEntitiesEntityIdTeamRouteImport.update({
    id: '/entities/$entityId/team',
    path: '/entities/$entityId/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdContractsRoute =
  AuthenticatedProjectsProjectIdContractsRouteImport.update({
    id: '/projects/$projectId/contracts',
    path: '/projects/$projectId/contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPartiesRoute =
  AuthenticatedProjectsProjectIdPartiesRouteImport.update({
    id: '/projects/$projectId/parties',
    path: '/projects/$projectId/parties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdReportsRoute =
  AuthenticatedProjectsProjectIdReportsRouteImport.update({
    id: '/projects/$projectId/reports',
    path: '/projects/$projectId/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRequestsRoute =
  AuthenticatedProjectsProjectIdRequestsRouteImport.update({
    id: '/projects/$projectId/requests',
    path: '/projects/$projectId/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdServicesRoute =
  AuthenticatedProjectsProjectIdServicesRouteImport.update({
    id: '/projects/$projectId/services',
    path: '/projects/$projectId/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdStagesRoute =
  AuthenticatedProjectsProjectIdStagesRouteImport.update({
    id: '/projects/$projectId/stages',
    path: '/projects/$projectId/stages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdVisitsRoute =
  AuthenticatedProjectsProjectIdVisitsRouteImport.update({
    id: '/projects/$projectId/visits',
    path: '/projects/$projectId/visits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/select-account': typeof SelectAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/entities/$entityId/invitations': typeof AuthenticatedEntitiesEntityIdInvitationsRoute
  '/entities/$entityId/report-templates': typeof AuthenticatedEntitiesEntityIdReportTemplatesRoute
  '/entities/$entityId/team': typeof AuthenticatedEntitiesEntityIdTeamRoute
  '/projects/$projectId/contracts': typeof AuthenticatedProjectsProjectIdContractsRoute
  '/projects/$projectId/parties': typeof AuthenticatedProjectsProjectIdPartiesRoute
  '/projects/$projectId/reports': typeof AuthenticatedProjectsProjectIdReportsRoute
  '/projects/$projectId/requests': typeof AuthenticatedProjectsProjectIdRequestsRoute
  '/projects/$projectId/services': typeof AuthenticatedProjectsProjectIdServicesRoute
  '/projects/$projectId/stages': typeof AuthenticatedProjectsProjectIdStagesRoute
  '/projects/$projectId/visits': typeof AuthenticatedProjectsProjectIdVisitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/select-account': typeof SelectAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/entities/$entityId/invitations': typeof AuthenticatedEntitiesEntityIdInvitationsRoute
  '/entities/$entityId/report-templates': typeof AuthenticatedEntitiesEntityIdReportTemplatesRoute
  '/entities/$entityId/team': typeof AuthenticatedEntitiesEntityIdTeamRoute
  '/projects/$projectId/contracts': typeof AuthenticatedProjectsProjectIdContractsRoute
  '/projects/$projectId/parties': typeof AuthenticatedProjectsProjectIdPartiesRoute
  '/projects/$projectId/reports': typeof AuthenticatedProjectsProjectIdReportsRoute
  '/projects/$projectId/requests': typeof AuthenticatedProjectsProjectIdRequestsRoute
  '/projects/$projectId/services': typeof AuthenticatedProjectsProjectIdServicesRoute
  '/projects/$projectId/stages': typeof AuthenticatedProjectsProjectIdStagesRoute
  '/projects/$projectId/visits': typeof AuthenticatedProjectsProjectIdVisitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/select-account': typeof SelectAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/_authenticated/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/entities/$entityId/invitations': typeof AuthenticatedEntitiesEntityIdInvitationsRoute
  '/_authenticated/entities/$entityId/report-templates': typeof AuthenticatedEntitiesEntityIdReportTemplatesRoute
  '/_authenticated/entities/$entityId/team': typeof AuthenticatedEntitiesEntityIdTeamRoute
  '/_authenticated/projects/$projectId/contracts': typeof AuthenticatedProjectsProjectIdContractsRoute
  '/_authenticated/projects/$projectId/parties': typeof AuthenticatedProjectsProjectIdPartiesRoute
  '/_authenticated/projects/$projectId/reports': typeof AuthenticatedProjectsProjectIdReportsRoute
  '/_authenticated/projects/$projectId/requests': typeof AuthenticatedProjectsProjectIdRequestsRoute
  '/_authenticated/projects/$projectId/services': typeof AuthenticatedProjectsProjectIdServicesRoute
  '/_authenticated/projects/$projectId/stages': typeof AuthenticatedProjectsProjectIdStagesRoute
  '/_authenticated/projects/$projectId/visits': typeof AuthenticatedProjectsProjectIdVisitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/select-account'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/invite/accept'
    | '/verify/$token'
    | '/projects/new'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/reports/$reportId'
    | '/requests/$requestId'
    | '/settings/security'
    | '/documents/'
    | '/properties/'
    | '/entities/$entityId/invitations'
    | '/entities/$entityId/report-templates'
    | '/entities/$entityId/team'
    | '/projects/$projectId/contracts'
    | '/projects/$projectId/parties'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/requests'
    | '/projects/$projectId/services'
    | '/projects/$projectId/stages'
    | '/projects/$projectId/visits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/select-account'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/invite/accept'
    | '/verify/$token'
    | '/projects/new'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/reports/$reportId'
    | '/requests/$requestId'
    | '/settings/security'
    | '/documents'
    | '/properties'
    | '/entities/$entityId/invitations'
    | '/entities/$entityId/report-templates'
    | '/entities/$entityId/team'
    | '/projects/$projectId/contracts'
    | '/projects/$projectId/parties'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/requests'
    | '/projects/$projectId/services'
    | '/projects/$projectId/stages'
    | '/projects/$projectId/visits'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/select-account'
    | '/_authenticated/dashboard'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/invite/accept'
    | '/verify/$token'
    | '/_authenticated/projects/new'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/properties/new'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/requests/$requestId'
    | '/_authenticated/settings/security'
    | '/_authenticated/documents/'
    | '/_authenticated/properties/'
    | '/_authenticated/entities/$entityId/invitations'
    | '/_authenticated/entities/$entityId/report-templates'
    | '/_authenticated/entities/$entityId/team'
    | '/_authenticated/projects/$projectId/contracts'
    | '/_authenticated/projects/$projectId/parties'
    | '/_authenticated/projects/$projectId/reports'
    | '/_authenticated/projects/$projectId/requests'
    | '/_authenticated/projects/$projectId/services'
    | '/_authenticated/projects/$projectId/stages'
    | '/_authenticated/projects/$projectId/visits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SelectAccountRoute: typeof SelectAccountRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-account': {
      id: '/select-account'
      path: '/select-account'
      fullPath: '/select-account'
      preLoaderRoute: typeof SelectAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/$requestId': {
      id: '/_authenticated/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/$entityId/invitations': {
      id: '/_authenticated/entities/$entityId/invitations'
      path: '/entities/$entityId/invitations'
      fullPath: '/entities/$entityId/invitations'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityIdInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/$entityId/report-templates': {
      id: '/_authenticated/entities/$entityId/report-templates'
      path: '/entities/$entityId/report-templates'
      fullPath: '/entities/$entityId/report-templates'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityIdReportTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/$entityId/team': {
      id: '/_authenticated/entities/$entityId/team'
      path: '/entities/$entityId/team'
      fullPath: '/entities/$entityId/team'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityIdTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/contracts': {
      id: '/_authenticated/projects/$projectId/contracts'
      path: '/projects/$projectId/contracts'
      fullPath: '/projects/$projectId/contracts'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/parties': {
      id: '/_authenticated/projects/$projectId/parties'
      path: '/projects/$projectId/parties'
      fullPath: '/projects/$projectId/parties'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPartiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/reports': {
      id: '/_authenticated/projects/$projectId/reports'
      path: '/projects/$projectId/reports'
      fullPath: '/projects/$projectId/reports'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/requests': {
      id: '/_authenticated/projects/$projectId/requests'
      path: '/projects/$projectId/requests'
      fullPath: '/projects/$projectId/requests'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/services': {
      id: '/_authenticated/projects/$projectId/services'
      path: '/projects/$projectId/services'
      fullPath: '/projects/$projectId/services'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/stages': {
      id: '/_authenticated/projects/$projectId/stages'
      path: '/projects/$projectId/stages'
      fullPath: '/projects/$projectId/stages'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdStagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/visits': {
      id: '/_authenticated/projects/$projectId/visits'
      path: '/projects/$projectId/visits'
      fullPath: '/projects/$projectId/visits'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRoute
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
  AuthenticatedRequestsRequestIdRoute: typeof AuthenticatedRequestsRequestIdRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedEntitiesEntityIdInvitationsRoute: typeof AuthenticatedEntitiesEntityIdInvitationsRoute
  AuthenticatedEntitiesEntityIdReportTemplatesRoute: typeof AuthenticatedEntitiesEntityIdReportTemplatesRoute
  AuthenticatedEntitiesEntityIdTeamRoute: typeof AuthenticatedEntitiesEntityIdTeamRoute
  AuthenticatedProjectsProjectIdContractsRoute: typeof AuthenticatedProjectsProjectIdContractsRoute
  AuthenticatedProjectsProjectIdPartiesRoute: typeof AuthenticatedProjectsProjectIdPartiesRoute
  AuthenticatedProjectsProjectIdReportsRoute: typeof AuthenticatedProjectsProjectIdReportsRoute
  AuthenticatedProjectsProjectIdRequestsRoute: typeof AuthenticatedProjectsProjectIdRequestsRoute
  AuthenticatedProjectsProjectIdServicesRoute: typeof AuthenticatedProjectsProjectIdServicesRoute
  AuthenticatedProjectsProjectIdStagesRoute: typeof AuthenticatedProjectsProjectIdStagesRoute
  AuthenticatedProjectsProjectIdVisitsRoute: typeof AuthenticatedProjectsProjectIdVisitsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedPropertiesPropertyIdRoute:
    AuthenticatedPropertiesPropertyIdRoute,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
  AuthenticatedRequestsRequestIdRoute: AuthenticatedRequestsRequestIdRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  AuthenticatedEntitiesEntityIdInvitationsRoute:
    AuthenticatedEntitiesEntityIdInvitationsRoute,
  AuthenticatedEntitiesEntityIdReportTemplatesRoute:
    AuthenticatedEntitiesEntityIdReportTemplatesRoute,
  AuthenticatedEntitiesEntityIdTeamRoute:
    AuthenticatedEntitiesEntityIdTeamRoute,
  AuthenticatedProjectsProjectIdContractsRoute:
    AuthenticatedProjectsProjectIdContractsRoute,
  AuthenticatedProjectsProjectIdPartiesRoute:
    AuthenticatedProjectsProjectIdPartiesRoute,
  AuthenticatedProjectsProjectIdReportsRoute:
    AuthenticatedProjectsProjectIdReportsRoute,
  AuthenticatedProjectsProjectIdRequestsRoute:
    AuthenticatedProjectsProjectIdRequestsRoute,
  AuthenticatedProjectsProjectIdServicesRoute:
    AuthenticatedProjectsProjectIdServicesRoute,
  AuthenticatedProjectsProjectIdStagesRoute:
    AuthenticatedProjectsProjectIdStagesRoute,
  AuthenticatedProjectsProjectIdVisitsRoute:
    AuthenticatedProjectsProjectIdVisitsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SelectAccountRoute: SelectAccountRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  VerifyTokenRoute: VerifyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
